title: Dan Olson's Blog
author: Dan Olson
description: Ramblings of a random software engineer.
show_excerpts: true
url: https://olson-dan.github.io
theme: minima
twitter:
  username: olson-dan
plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post
minima:
  # generate social links in footer
  social_links:
    twitter: olson-dan
    github:  olson-dan
    rss: rss