name: Dan Olson's Blog
description: Sorry it doesn't have a fancy name.
url: https://olson-dan.github.io
theme: minima
twitter:
  username: olson-dan
plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post